### ISSUE TITLE
Recent upgrade to Gurobi 7.5.0 - Unable to retrieve attributes

### ISSUE THREAD

**Issue by resigmike** [coin-or/pulp#141]
I recently updated my Gurobi to the newest 7.5.0 version. After running two previously reliable PuLP models with known results (optimal and infeasible), PuLP returns an error with both after attempting to acquire attributes from Gurobi. These errors disrupt the PuLP model from completing or displaying the results, even though the models successfully processed in Gurobi:

AttributeError: Unable to retrieve attribute 'X'
AttributeError: Unable to retrieve attribute 'RC'

These errors appear at the completion of the model.solve(pulp.GUROBI()), prior to any other line. Is this a common issue that appears with solver updates? Please disregard this message if it does not qualify as a PuLP issue.

**Comment by stumitchell** [comment]
Bugger, is this with the lastest version of pulp?

https://pypi.python.org/pypi?:action=display&name=PuLP&version=1.6.7

**Comment by stumitchell** [comment]
Right this was due to python changing the error returned when an attribute is not present from gurobipy.GurobiError to AttributeError.

I have managed to introduce and fix in https://github.com/coin-or/pulp/commit/60ee1c791f16d6571feadefd5a4c58b19d96e9fe released as 1.6.8 so please test to see if this fixes your problem.

**Comment by resigmike** [comment]
I was able to test multiple models with success - no more error logs from Gurobi! Thank you very much for the quick patch and your attentiveness, it is much appreciated.
