### ISSUE TITLE
Higher floating point precision results?

### ISSUE THREAD

**Issue by martiansideofthemoon** [coin-or/pulp#147]
I am using `pulp` to solve a linear programming problem based on [this case study](https://pythonhosted.org/PuLP/CaseStudies/a_blending_problem.html).  All the optimized values are rounded to 7 decimal places, such as `2.6094675`. Is it possible to get results having a higher accuracy?

**Comment by s-c-e** [comment]
Maybe it's a bit of a "hack" but what if you were to reformulate the problem, scaling your decision variables by a factor of, for example, 1000?

Then, in your example, you'd still have something rounded to seven decimal places but the optimized value would look like `2609.4675111` - you'd gain those extra three decimal places.

I'm no expert, but things like the precision of your inputs, the solver's stopping threshold, or etc. may affect if those extra digits are even meaningful, however.

**Comment by stumitchell** [comment]
Because pulp uses floating point arithmetic to produce results I would not trust results to really be accurate to the 7th decimal place. If you look at the solution you will often see that constraints are violated by small amounts and this is just because of the calculations going on in the solver.

So I would try to scale your problem better or look at another way of solving it.

Stu
