### ISSUE TITLE
Constraints only considered when there's an equal to symbol included 

### ISSUE THREAD

**Issue by jignyasi** [coin-or/pulp#163]
Consider "x" an integer ranging between 0 to 10.
Objective is: x + 10
Problem is: Minimize
Constraint: x > 4.1
Expected Result: x = 5, obj = 15
Obtained Result: x = 0, obj = 10
Code:
```python
from pulp import *
prob = LpProblem("test1", LpMinimize)
x = LpVariable("x", 0, 10, 'Integer')
prob += x + 10, "obj"
prob += x > 4.1, "c1"
prob.solve()
print("Status:", LpStatus[prob.status])
print(prob.variables()[0].name, "=", prob.variables()[0].varValue)
print("objective=", value(prob.objective))
```
I've observed that by changing the constraint from ">" to ">=" and it worked as expected.

Code:
```python
from pulp import *
prob = LpProblem("test1", LpMinimize)
x = LpVariable("x", 0, 10, 'Integer')
prob += x + 10, "obj"
prob += x >= 4.1, "c1"   #Changed the constraint from > to >=
prob.solve()
print("Status:", LpStatus[prob.status])
print(prob.variables()[0].name, "=", prob.variables()[0].varValue)
print("objective=", value(prob.objective))
```
Obtained Result: x = 5, obj = 15

**Comment by SephDB** [comment]
PuLP only has three types of constraints: LpConstraintEqual, LpConstraintGE and LpConstraintLE(for ==, >= and <=, respectively).
The reasoning for this is that it can also deal with floating point values, and giving you the "next" floating point for a > constraint is not really nice(and a lot of the underlying solvers don't implement that kind of constraint for this reason).
The fact that you didn't get an error using > instead of >= is something that could(should?) probably be fixed.

**Comment by jignyasi** [comment]
Thanks for the clarification.
If not an error, maybe throwing a warning might help.
