### ISSUE TITLE
MIP Infeasible Status is wrong with PULP_CBC_CMD

### ISSUE THREAD

**Issue by SaitoTsutomu** [coin-or/pulp#171]
cbc's MIP Infeasible Statu is `Integer infeasible - objective value ...`.
This recognized `LpStatusUndefined`.

**Comment by SaitoTsutomu** [comment]
```
--- a/src/pulp/solvers.py
+++ b/src/pulp/solvers.py
@@ -1474,6 +1474,7 @@ class COIN_CMD(LpSolver_CMD):
         slacks = {}
         cbcStatus = {'Optimal': LpStatusOptimal,
                     'Infeasible': LpStatusInfeasible,
+                    'Integer': LpStatusInfeasible,
                     'Unbounded': LpStatusUnbounded,
                     'Stopped': LpStatusNotSolved}
         with open(filename) as f:
@@ -1509,6 +1510,7 @@ class COIN_CMD(LpSolver_CMD):
             values[v.name] = 0.0
         cbcStatus = {'Optimal': LpStatusOptimal,
                     'Infeasible': LpStatusInfeasible,
+                    'Integer': LpStatusInfeasible,
                     'Unbounded': LpStatusUnbounded,
                     'Stopped': LpStatusNotSolved}
         with open(filename) as f:
```

**Comment by dymov** [comment]
Generally, PULP_CBC_CMD seems to have a hard time recognizing solution statuses. There are many more cases and probably a more systematic approach is needed. 

E.g. 
"Result - Stopped on solution limit", "Result - Stopped on time limit" gets the status 0, which is mapped to "Not Solved" - not very helpful, since in case of solution limits, there can still be a valid (albeit not proven optimal) solution.

If anyone is interested, I can try to produce example LP files that produce these cases.
