### ISSUE TITLE
get A and b from PuLP

### ISSUE THREAD

**Issue by SanPen** [coin-or/pulp#216]
Hi, 

I would like to know if it is possible to extract a linear program's associated matrix `A` and the vector `b`.

My aim is to try [this](https://scaron.info/blog/linear-programming-in-python-with-cvxopt.html).

**Comment by pchtsp** [comment]
I don't think you can obtain the matrix. Many times, it wouldn't even fit
in memory.

In the link you provided the examples used were really small problems.
Here, pulp's CBC takes more time because it needs to write a file to disk.

If you want to speed the construction of the problem and the call to the
solver from pulp there are many options. The easier is to use a ram disk
(follow
https://groups.google.com/forum/#!searchin/pulp-or-discuss/file$20time%7Csort:date/pulp-or-discuss/b-d-Xjm7-Xw/aOdouZLpCAAJ
I
have never tried this). Other alternatives include using COINMP_DLL solver
which is also CBC but using the dll instead of the command line to call it.

Important: if your problem is really big (CBC takes minutes, hours, or
more) changing to any of the solvers in that link won't help you.

**Comment by SanPen** [comment]
Well my idea is to test the linked code, and implement barrier with parallel matrix products and factorization, wich would possibly provide performance improvements.

My current problem with CBC is that it uses only single threading, even though there could be an option to use parallel blas/lapack operations. 
So I want to at least try by my self using theano maybe, and to do that I need to generate `A` and `b`.

**Comment by SanPen** [comment]
`A` should be in CSC (or CSR) sparse format, and `b` should be dense I assume. 
If you could please indicate which functions compute these, I'll have a look at what I can do.

**Comment by tkralphs** [comment]
I'm certainly not an expert on PuLP and someone else may have a better idea, but the `writeLP` function is [here](https://github.com/coin-or/pulp/blob/183dbdff3f6a4e559af8d503752c27c95b0c2a00/src/pulp/pulp.py#L1503) and from that, you should be able to see how to extract the constraint matrix from PuLP's internal data structures.
