### ISSUE TITLE
Numpy-based array interface to pulp

### ISSUE THREAD

**Issue by qdbp** [coin-or/pulp#285]
I would like to probe interest in the inclusion into mainline pulp of a **numpy-based array-oriented interface to collections of lp varibles and constraints**. Specifically, I've written a small helper library, [pulp-lparray](https://github.com/qdbp/pulp-lparray) to make working with arrays of LpVariables more intuitive, which I propose be included in pulp.

Pulp is very user-friendly, but I found its dict-based nature cumbersome and anti-idiomatic for working with multidimensional grids of variables. Numpy provides fantastic primitives for vectorized operations and implicit loops, and I wanted to leverage those to make my pulp code more terse and intuitive. An example of what my library looks like:

```
    sell_qty_limit = np.array([-t.qty for t in sells], dtype=np.uint32)
    buy_qty_limit = np.array([t.qty for t in buys], dtype=np.uint32)

    prob = LpProblem(sense=LpMinimize)
    match: lparray = lparray.create_anon("Match", (nb, ns), cat=LpInteger, lowBound=0)

    (match.sum(axis=0) <= sell_qty_limit).constrain(prob, "SellLimit")
    (match.sum(axis=1) <= buy_qty_limit).constrain(prob, "BuyLimit")

    cost = (match * loss).sumit()
    prob += cost
```

Another good example is the "SuperSudoku" on the readme page.

In addition to terser, less noisy syntax, `lparray` provides some backend-agnostic primitives such as min, max, abs, binarization, etc. These are less developed as I've added them mostly as the need comes up rather than in a systematic way.

I think that pulp will benefit from having an interface like this, but I don't want to send an unsolicited PR without consulting the community.

**Comment by tkralphs** [comment]
[CyLP](https://github.com/coin-or/CyLP) has a really great numpy-based modeling capability and I have actually been thinking about whether it would make sense to merge parts of it with PuLP or [python-mip](https://github.com/coin-or/python-mip). Right now, CyLP only interfaces to Clp/Cbc, mainly because it provides really low-level API access through a Cython-based interface. The modeling parts of it are in pure Python, though. Food for thought.

**Comment by stumitchell** [comment]
Interesting,

we can have a think about naming, maybe `pulp.lparray`

I would prefer if it was a separate library as we are moving stuff out of
pulp into side libraries atm (like amply)

Stu

**Comment by pchtsp** [comment]
Hello there,

Myself I've going an alternative route with a package I created called `pytups`. It consists on a wrapper on dictionaries and lists of tuples to be able to wrangle with the data in a vectorized, functional programming way (like R or numpy). I started to use it for pulp but I know use it for anything that involves working with data (pre-process and post-process). It avoids most for-loops by doing list and dict comprehensions under the hood. When I've compared it with numpy I've found that most times it does just as fast or faster and the chaining capabilities are very comfortable to work with:

Altough this package does not have `pulp` as dependency, it does use numpy and I've always wondered if I should have `numpy` as an alternative backend for the functions.

An example of using it on a small scheduling problem with pulp:

https://pchtsp.github.io/pytups/pulp.html#implementation-using-pulp-and-pytups

I'm just mentioning this because we could potentially evaluate the relevance of merging some of the projects, in case we see there is something useful.

F.

**Comment by qdbp** [comment]
> Interesting, we can have a think about naming, maybe `pulp.lparray` I would prefer if it was a separate library as we are moving stuff out of pulp into side libraries atm (like amply) Stu

Keeping it as a separate library seems easier in terms of maintenance. In that case my goal would be for `lparray` to become discoverable from the official PuLP documentation as an alternate interface, and correspondingly to focus on features complementary to the base PuLP -- namely, succinct operations on homogeneous grids of LpVariables.

I like PuLP and can't speak for alternatives such as python-mip or CyLP. Based on a quick look, the lparray class serves the same goal as CyLPArray except with more methods implemented (like abs, max, etc.) Clearly if you're using CyLP then lparray is useless, and the same goes for other frameworks.

Personally, however, I like PuLP for its simplicity, and I don't see myself moving. And if it's worth keeping PuLP around as a separate library, then I think lparray has a place beside it.

**Comment by pchtsp** [comment]
Perfect, thanks.
I'm closing this issue. Maybe one day we should add compatible projects in the docs, like extensions. And refer to `lparray`.
