### ISSUE TITLE
Pulp causes start-up of cloud gurobi server upon import, even if not using gurobi as a solver 

### ISSUE THREAD

**Issue by simon-b** [coin-or/pulp#345]
Details for the issue
--------------------

I have gurobipy installed and a valid gurobi licence. However, when using pulp I do not necessarily plan to use gurobi. Therefore I think it is reasonable that unless I specify gurobi as a solver, pulp should not attempt to "use" gurobi in any way. In particular if I have a cloud licence, I would not want pulp to start up any cloud resources unless I am actually using gurobi as a solver.

The following line that executes at import time however does result in gurobi "use":  
https://github.com/coin-or/pulp/blob/2.3/pulp/apis/gurobi_api.py#L53

#### What did you do?

`import pulp`

#### What did you expect to see?

Pulp immediately imported, and no reach out to any remote gurobi servers.

#### What did you see instead?

I must wait ~1m and I can see that gurobi reaches out to requires start up of some cloud resources.
Partially obfuscated log below:

```bash
> time python -c "import pulp"
Using license file /XXX/gurobi.lic
Set parameter CloudAccessID
Set parameter CloudSecretKey
Set parameter CloudPool to value XXX
Waiting for cloud server to start (pool XXX)...
Starting...
Starting...
Starting...
Starting...
Compute Server job ID: XXX
Capacity available on 'XXX' cloud pool - connecting...
Established HTTPS encrypted connection
No parameters matching '_test' found

Compute Server communication statistics:
  Sent: 0.001 MBytes in 9 msgs and 3.12s (0.00 MB/s)
  Received: 0.001 MBytes in 4 msgs and 2.46s (0.00 MB/s)

python -c "import pulp"  0.14s user 0.10s system 0% cpu 57.943 total
```  

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 10.15.6 )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.7

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

#### Did you also

- [x] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Thanks for the report.

I get your point, I had not tested it with gurobi cloud resources so I did not know that this happened.

We use that line as a dirty way to test for a valid gurobi license since even if the python library is available, the solver could fail because the license is not valid. I guess we could move that command to the `available` function and return `False` if it raises a license error. That way it will only make that call when someone explicitly asks if the solver is available.

If you want a temporary workaround, you can change the gurobi environment variables during the session so as to point to your local machine (instead of the cloud resources) if you know you will not be using gurobi.

Can you confirm that the problem happens with the `gurobipy.setParam("_test", 0)` only? Or does the `import gurobipy` line also make a call to the gurobi server ?

As a side note, do you know of a better way to ask gurobi if the license is valid ? I'm interested for both apis (the gurobi python api and the gurobi command line api).

Thanks again

**Comment by simon-b** [comment]
I can confirm that importing gurobipy alone does not cause the problem. As far as I observe in my usual usage, it reaches out when I create a gurobi model or `gurobi.Env()`, or in this case when trying to set a parameter.  

I don't know of any way to check if a licence is "valid", short of trying to actually use it. However given that cloud licences contain a `CloudAccessID` and `CloudSecretKey`, and I believe compute server licences contain an IP and password, I wouldn't expect it to be possible to test locally whether the licence is valid: you'd have to reach out to check e.g. if the password is correct.
