### ISSUE TITLE
LpAffineExpression.__init__ is way too slow

### ISSUE THREAD

**Issue by jachymb** [coin-or/pulp#362]
This piece of code causes a slowdown in `LpAffineExpression.__init__` function which can be noticeable for problems with many long constraints. (It is a major bottleneck in my application):

```python
        elif isinstance(e, dict):
            self.constant = constant
            super(LpAffineExpression, self).__init__(list(e.items()))
```

A faster implementation would be: 

```python
        elif isinstance(e, dict):
            self.constant = constant
            super(LpAffineExpression, self).__init__(e)
```

Although the later is faster, both these still need O(`len(e)`) time to run as it still makes a copy of `e`.  In my opinion, even better solution would be using the dictionary `e` as an attribute instead of subclassing dict as that would run in O(1) but that would obviously required a significantly bigger code change.

As a side note, the function contains the following comment:
```# TODO remove isinstance usage```
I suspect the multiple `isinstance` calls are further hindering the performance, although that's only a constant slowdown for each call it would be nice to see that improved as well.

**Comment by pchtsp** [comment]
Have you tried changing the code and checking it does not brake anything? I'm fairly confident that the copying is needed in order to be able to chain the operations.

In case you do care about performance and do not want to do extra copies, try what is explained in this SO post: https://stackoverflow.com/questions/64494385/cannot-reduce-time-taken-to-add-constraints-to-pulp/64497199#64497199
