### ISSUE TITLE
GLPK is not being recognized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#42]
```
I am trying to install GLPK and run it as my PuLP solver. I have added the 
location of glpsol to my path by adding a .pth file to the site-packages folder 
in the Lib folder of my Python27 folder.

What is the expected output? What do you see instead?
I expect to see that GLPK_CMD is available when I run pulpTestAll(), but I 
always see it as unavailable.

What version of the product are you using? On what operating system?
I am using python 2.7 and the newest version of PuLP.
```

Original issue reported on code.google.com by `kyle.w.a...@gmail.com` on 9 Jun 2012 at 3:52

**Comment by huanfachen** [comment]
I am using python 2.7 with PuLP and GLPK on windows. Managed to make PuLP run with the GLPK solver.
There are two ways to achieve this:

1. In the pulp.cfg.win file, set **GlpkPath = C:\Program Files\winglpk-4.65\glpk-4.65\w64\glpsol**. Change the path as necessary.
2. In the environment setting of user variables, add **C:\Program Files\winglpk-4.65\glpk-4.65\w64** to the path variable. Then, in the pulp.cfg.win file, delete (or comment via hashtag) the line of **GlpkPath** so that the programme searches system settings to find the glpk path.

**Comment by nadershehata95** [comment]
> I am using python 2.7 with PuLP and GLPK on windows. Managed to make PuLP run with the GLPK solver. There are two ways to achieve this:
> 
>     1. In the pulp.cfg.win file, set **GlpkPath = C:\Program Files\winglpk-4.65\glpk-4.65\w64\glpsol**. Change the path as necessary.
> 
>     2. In the environment setting of user variables, add **C:\Program Files\winglpk-4.65\glpk-4.65\w64** to the path variable. Again, change the above path as necessary. Then, in the pulp.cfg.win file, delete (or comment via hashtag) the line of **GlpkPath** so that the programme searches system settings to find the glpk path.

I am very sorry but can you explain more the first step cause I can't understand it what is pulp.cfg.win file? where can I find that
