### ISSUE TITLE
unsupported operand type(s) for /: 'LpVariable' and 'int'

### ISSUE THREAD

**Issue by senarclens** [coin-or/pulp#84]
Used version: 1.5.9
For some reason it is currently not allowed to divide an LpVariable by an int. This can be easily circumvented by multiplying an entire constraint set w/ that integer - however I don't see why it shouldn't be allowed in the first place.

Test Case:
import pulp
a = pulp.LpVariable('f^min', lowBound=0, cat=pulp.LpContinuous)
milp = pulp.LpProblem("TC", pulp.LpMinimize)
milp += a
milp += a / 2 >= 0.5

Actual Result:
TypeError: unsupported operand type(s) for /: 'LpVariable' and 'int'

Expected Result:
test case works as expected w/ optimum a = 1

**Comment by dassouki** [comment]
I am not sure if the issue is in [one of the two functions (div and __trueidv__)](https://github.com/coin-or/pulp/blob/master/src/pulp/pulp.py#L797 ).

I even tried multiple scenarios such as 1/2 * a, (1/2) * a, a * (1/2) and still with no error posted. 

Perhaps the correct procedure would be to scan all the constraints and objective functions for numerical fractions and compute those prior to prob.solve() ?

**Comment by alansun17904** [comment]
I am also having the same problem. I can't take the modulus of the sum of a group of lpVariables.
Test Case:
```python
import pulp
model = pulp.LpProblem('Time table', pulp.LpMaximize)
status = pulp.LpVariable.dicts('status', 
                            ((person, event) for peron in PERSONS for event in allTimes), 
                            cat='Binary')
# constraint
model += sum([status[(people, '4:00-6:00')] for people in PERSONS]) % 4 == 0
```
Error:
```python
TypeError: unsupported operand type(s) for %: 'LpAffineExpression' and 'int'
```

**Comment by stumitchell** [comment]
Sorry as this operation can't be directly translated into a constraint the modulo operation should not be allowed.
